context:
  version: "0.3.30"

package:
  name: codebook-lsp
  version: ${{ version }}

source:
  url: https://github.com/blopker/codebook/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d7285193a902cbde672c72626f732ec8be6f1e5b4d927f3d15a3d37a82af8010

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then: |
          export CFLAGS="${CFLAGS} -D_BSD_SOURCE"
          cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
          cargo auditable install --locked --no-track --path ./crates/codebook-lsp --root ${PREFIX}
        else: |
          cargo-bundle-licenses --format yaml --output %SRC_DIR%\THIRDPARTY.yml
          cargo auditable install --locked --no-track --path .\crates\codebook-lsp --root %LIBRARY_PREFIX%

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - codebook-lsp --version

about:
  homepage: https://github.com/blopker/codebook
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: "Spell Checker for Code"
  summary: "Spell Checker for Code"

extra:
  recipe-maintainers:
    - VasanthakumarV
